import { Agreement, SignetExport } from './types';
import { getRoleDisplayName } from './types';
import { roleStorage } from './storage';
import { getCommitment, getPartyRoleIds } from './agreementHelpers';

export async function generateSignetExport(agreement: Agreement): Promise<SignetExport | null> {
  const partyRoleIds = getPartyRoleIds(agreement);
  const roles = await Promise.all(partyRoleIds.map((id) => roleStorage.findById(id)));
  if (roles.some((r) => !r)) {
    return null;
  }

  const currentVersion = agreement.versions[agreement.currentVersion];
  if (!currentVersion) {
    return null;
  }

  const parties = roles.map((role) => {
    const name = getRoleDisplayName(role!);
    return {
      roleId: role!.id,
      roleName: role!.template?.name ?? name,
      playerName: role!.playerName,
      commitment: getCommitment(currentVersion, role!.id),
    };
  });

  const signetExport: SignetExport = {
    agreementId: agreement.id,
    exportedAt: new Date().toISOString(),
    parties,
    terms: {
      commitments: currentVersion.commitments,
      agreementNotes: currentVersion.notes,
    },
    signatures: parties.map((party) => ({
      roleId: party.roleId,
      name: party.playerName ?? party.roleName,
      signedAt: new Date().toISOString(),
    })),
    legalText: generateLegalText(parties, currentVersion.notes),
  };

  return signetExport;
}

function generateLegalText(
  parties: SignetExport['parties'],
  notes: string
): string {
  const partyList = parties.map((p) => p.playerName ?? p.roleName).join(', ');
  const commitmentLines = parties
    .map((p, i) => `${i + 1}. ${p.roleName} commits to: ${p.commitment}`)
    .join('\n');

  return `
INFRASTRUCTURE AGREEMENT

This Infrastructure Agreement ("Agreement") is entered into between ${partyList}.

COMMITMENTS:
${commitmentLines}

COMBINED EFFECT:
${notes || 'No combined effect specified.'}

REPRESENTATIONS:
Each party represents that they have the authority to enter into this Agreement and that their commitments reflect their role obligations within the DWeb Nomad Infrastructure network.

ENTIRE AGREEMENT:
This Agreement constitutes the entire agreement between the parties regarding the subject matter herein.

Generated by Polycentric on ${new Date().toLocaleDateString()}
  `.trim();
}

export function downloadSignetExport(signetExport: SignetExport): void {
  const jsonString = JSON.stringify(signetExport, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `polycentric-agreement-${signetExport.agreementId}-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

export async function exportAgreement(agreement: Agreement): Promise<{ success: boolean; error?: string }> {
  if (agreement.status !== 'approved' && agreement.status !== 'completed') {
    return { success: false, error: 'Can only export approved or completed agreements' };
  }

  const signetExport = await generateSignetExport(agreement);
  if (!signetExport) {
    return { success: false, error: 'Failed to generate export data' };
  }

  try {
    downloadSignetExport(signetExport);
    return { success: true };
  } catch {
    return { success: false, error: 'Failed to download export file' };
  }
}
