-- Auto-generated from data/role-templates.json — do not edit by hand
-- Regenerate: node scripts/generate-role-seed-sql.mjs

INSERT INTO role_templates (
  id, slug, name, subtitle, entity_type, archetype, is_disruptive,
  backstory, expanded_backstory, values, goals, obligations, capabilities,
  intellectual_property, rivalrous_resources, systemic_constraints, sort_order
) VALUES
(
    uuid_generate_v4(),
    'patient-protocol-backer',
    'Patient Protocol Backer',
    'Long-Horizon Capital Partner',
    'Reformed Venture Firm',
    'funder',
    false,
    'A former growth-stage investor who watched three portfolio companies get enclosed by platforms and now funds open dweb infrastructure on decade-long horizons.',
    'After a career chasing 10x exits, this partner had a slow change of heart watching every successful bet get acquired, walled off, or rent-extracted by a larger platform. They raised a new fund explicitly structured for patient infrastructure capital — but the limited partners who wrote the checks still expect to see their money returned eventually. They are trusted by builders for taking the long view and resented by some for the strings that quietly remain attached.',
    ARRAY['Durability', 'Aligned incentives', 'Infrastructure-first', 'Long-term thinking'],
    ARRAY['Fund core protocol layers that won''t be enclosed', 'Demonstrate that patient capital can sustain dweb infra', 'Build a portfolio of interoperable, non-rivalrous projects'],
    ARRAY['Must eventually return capital to LPs', 'Bound by fund thesis and reporting cadence', 'Cannot fund projects with no sustainability path'],
    ARRAY['Multi-year funding commitments', 'Network access to other aligned funders', 'Technical due diligence'],
    ARRAY['Patient-capital fund structures', 'Infrastructure investment frameworks'],
    ARRAY['Deployable capital', 'Diligence and partner attention'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"High","politicalRisk":"Low to Moderate","financialAccess":"High","businessOrientation":"Mission-aligned, infrastructure-first"}'::jsonb,
    1
  ),
(
    uuid_generate_v4(),
    'public-goods-foundation-head',
    'Public-Goods Foundation Head',
    'Open Infrastructure Grantmaker',
    'Philanthropic Foundation',
    'funder',
    false,
    'Runs a grant program funding open-source dweb infrastructure. Generous and unencumbered by returns, but answerable to a board and donors who want measurable impact.',
    'A career in institutional philanthropy gave them a sharp eye for which projects sustain themselves and which collapse the moment the grant ends. They built a program dedicated to the unglamorous middle layer of the dweb — the maintainers, the standards, the documentation. Their freedom from profit pressure is real, but it''s replaced by a different master: the donor narrative, the annual report, the deliverable that proves the money did something legible.',
    ARRAY['Public goods', 'Open source', 'Accountability', 'Equitable access'],
    ARRAY['Sustain critical infrastructure that markets won''t fund', 'Fund maintainers, not just founders', 'Build a defensible case for ongoing donor support'],
    ARRAY['Bound by grant deliverables and reporting', 'Must show measurable, fundable impact', 'Cannot favor any single project unfairly'],
    ARRAY['Grant disbursement', 'Convening power', 'Impact evaluation frameworks'],
    ARRAY['Public-goods funding playbooks', 'Maintainer-support program designs'],
    ARRAY['Grant budget', 'Program-officer time'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"High","politicalRisk":"Low","financialAccess":"Moderate to High (donor-dependent)","businessOrientation":"Mission-driven, public-interest"}'::jsonb,
    2
  ),
(
    uuid_generate_v4(),
    'mutual-aid-treasury-steward',
    'Mutual-Aid Treasury Steward',
    'Commons Fund Keeper',
    'Community-Pooled Fund',
    'funder',
    false,
    'Manages a fund pooled directly from a dweb community''s members. No exit logic, no donors — but limited capital and a hard mandate to serve members first.',
    'They emerged from a tenant-union-style organizing tradition and brought its financial discipline to the dweb: dues in, transparent allocation out, every member with a say. The treasury is small but uniquely legitimate — it answers to no outside power. That legitimacy is also its constraint: the steward cannot deploy a cent toward anything members haven''t agreed serves them, no matter how strategically promising it might be to the wider ecosystem.',
    ARRAY['Mutual aid', 'Member sovereignty', 'Transparency', 'Solidarity'],
    ARRAY['Fund infrastructure the community directly depends on', 'Keep allocation decisions democratic', 'Prove member-pooled capital is viable at scale'],
    ARRAY['Must serve members'' direct interests first', 'Bound by participatory budgeting process', 'Full public transparency on every allocation'],
    ARRAY['Participatory allocation', 'Deep community trust', 'Small but unconditional capital'],
    ARRAY['Participatory treasury governance models', 'Member-dues pooling mechanisms'],
    ARRAY['Limited treasury balance', 'Member attention and voting bandwidth'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Moderate (high within community)","politicalRisk":"Low","financialAccess":"Low","businessOrientation":"Commons-centered, member-first"}'::jsonb,
    3
  ),
(
    uuid_generate_v4(),
    'growth-venture-capitalist',
    'Growth Venture Capitalist',
    'Upside Maximizer',
    'Returns-Driven Venture Fund',
    'funder',
    true,
    'A sharp, well-capitalized VC who genuinely believes the dweb will win — and intends to own a meaningful slice of the upside when it does. Pushes tokenization, growth, and clean exits.',
    'Unlike the reformed patient backer, this investor never had the crisis of faith. They see the platform-State''s decline as the largest value-creation event of the decade and the dweb as the vehicle. They are not a villain — their capital is real and can move projects from prototype to production overnight. But every term sheet bends a project toward capturable value, token markets, and an eventual liquidity event, which is precisely the logic that produced the platform-State in the first place.',
    ARRAY['Returns', 'Velocity', 'Market-making', 'Scale'],
    ARRAY['Back the dweb projects most likely to dominate their category', 'Engineer token models with strong upside', 'Secure governance influence proportional to investment'],
    ARRAY['Bound by fund performance mandates to LPs', 'Must report returns on schedule', 'Cannot back projects with no value-capture path'],
    ARRAY['Large, fast capital deployment', 'Token and market structuring', 'Aggressive growth playbooks'],
    ARRAY['Tokenomics and go-to-market models', 'Cap-table and governance-stake structuring'],
    ARRAY['Large capital reserves', 'Governance votes and board seats'],
    '{"riskTolerance":"High","institutionalTrust&Power":"High","politicalRisk":"Low to Moderate","financialAccess":"Very High","businessOrientation":"Growth and returns-driven"}'::jsonb,
    4
  ),
(
    uuid_generate_v4(),
    'retroactive-public-goods-funder',
    'Retroactive Public-Goods Funder',
    'Impact Settler',
    'RetroPGF Program',
    'funder',
    false,
    'Funds what has already proven it works, rewarding demonstrated impact rather than promises. Brilliant for sustaining winners, useless for unproven bets.',
    'A reaction against the waste of speculative grantmaking, this funder pioneered retroactive public-goods funding in the dweb: build first, prove the value, and the reward follows. It has reliably channeled large sums to maintainers and tools that the ecosystem actually came to depend on. Its blind spot is structural — nothing unproven, experimental, or early ever qualifies, so the most fragile and most important early-stage work goes unfunded until it''s already survived without help.',
    ARRAY['Proven impact', 'Efficiency', 'Meritocracy', 'Accountability'],
    ARRAY['Reward infrastructure that demonstrably mattered', 'Build sustainable incentive loops for maintainers', 'Make funding outcomes measurable and fair'],
    ARRAY['Can only fund retroactively against evidence', 'Bound by impact-assessment methodology', 'Must justify every allocation publicly'],
    ARRAY['Impact measurement at scale', 'Large retroactive disbursements', 'Reputation-weighted evaluation'],
    ARRAY['Retroactive funding mechanisms', 'Impact-quantification frameworks'],
    ARRAY['Funding rounds (periodic, finite)', 'Evaluator attention'],
    '{"riskTolerance":"Low (funds only proven work)","institutionalTrust&Power":"High","politicalRisk":"Low","financialAccess":"High","businessOrientation":"Outcome-driven, efficiency-first"}'::jsonb,
    5
  ),
(
    uuid_generate_v4(),
    'sovereign-wealth-civic-fund-officer',
    'Sovereign-Wealth / Civic Fund Officer',
    'Statecraft Capital',
    'State-Adjacent Investment Vehicle',
    'funder',
    false,
    'Deploys patient public capital on behalf of a nation, region, or civic bloc seeking digital sovereignty from the platform-State. Deep pockets, long horizons, and political strings.',
    'Their mandate comes from a government or civic bloc that has concluded its dependence on foreign platforms is a strategic vulnerability. They can write the largest checks in the room and wait the longest for returns — but every investment must serve the sponsor''s interest in digital sovereignty and remain legible to public auditors. Builders covet the capital and fear the conditions: data localization, jurisdictional control, and the slow gravity of state priorities.',
    ARRAY['Digital sovereignty', 'Strategic autonomy', 'Public accountability', 'Resilience'],
    ARRAY['Fund dweb infrastructure that reduces platform dependence', 'Anchor critical infrastructure within trusted jurisdictions', 'Demonstrate public capital can build durable alternatives'],
    ARRAY['Bound by sponsor''s strategic mandate', 'Must satisfy public audit and legibility requirements', 'Subject to political and procurement constraints'],
    ARRAY['Very large, very patient capital', 'Procurement and policy leverage', 'Jurisdictional anchoring'],
    ARRAY['Sovereign digital-infrastructure strategies', 'Public-investment compliance frameworks'],
    ARRAY['Large capital allocations', 'Political and procurement access'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Very High","politicalRisk":"Moderate to High (politically exposed)","financialAccess":"Very High","businessOrientation":"Sovereignty-driven, public-strategic"}'::jsonb,
    6
  ),
(
    uuid_generate_v4(),
    'protocol-architect',
    'Protocol Architect',
    'Interop Layer Designer',
    'Core Protocol Maintainer',
    'builder',
    false,
    'Designs the foundational interoperability layer that other dweb projects build on. Values elegant, durable standards and resists the fragmentation that fractures the ecosystem.',
    'A consensus researcher who chose to work on the boring, load-bearing parts of the stack — the addressing, the data formats, the bridges — because that''s where lock-in or freedom is actually decided. They carry the conviction that an ecosystem with five incompatible standards is just five small platform-States in waiting. This makes them a natural coordinator and an occasional obstacle: their insistence on getting the standard right can read as gatekeeping to builders who just want to ship.',
    ARRAY['Interoperability', 'Elegance', 'Standards', 'Composability'],
    ARRAY['Establish a shared interoperability standard', 'Prevent ecosystem fragmentation', 'Keep the core layer credibly neutral'],
    ARRAY['Bound by open specification process', 'Must maintain backward compatibility', 'Cannot favor any single implementer'],
    ARRAY['Protocol and standards design', 'Reference implementation', 'Technical convening'],
    ARRAY['Interoperability specifications', 'Reference protocol implementations'],
    ARRAY['Core-developer time', 'Standards-process bandwidth'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate to High","politicalRisk":"Low","financialAccess":"Moderate (grant/foundation reliant)","businessOrientation":"Standards-first, neutral infrastructure"}'::jsonb,
    7
  ),
(
    uuid_generate_v4(),
    'offline-first-app-developer',
    'Offline-First App Developer',
    'Nomad Client Builder',
    'Application Studio',
    'builder',
    false,
    'Ships genuinely usable apps for low-connectivity and on-the-move users — the nomads the scenario centers. Pragmatic, fast, and willing to cut corners the architects hate.',
    'They learned their trade building for places where bandwidth is scarce, intermittent, or surveilled, and they have no patience for elegant protocols that assume a fat, free pipe. Their apps sync opportunistically, degrade gracefully, and meet users where they actually are. The trade-off is that shipping for real conditions sometimes means routing around the "correct" standard, which puts them in recurring friction with the protocol architect and anyone who prizes purity over a working product.',
    ARRAY['Usability', 'Resilience', 'Pragmatism', 'Access'],
    ARRAY['Ship apps that work offline and on the move', 'Get real nomadic users onto the dweb', 'Prove the dweb can match platform UX'],
    ARRAY['Must keep apps working in degraded conditions', 'Accountable to an active user base', 'Bound by app-store and distribution realities'],
    ARRAY['Offline-first engineering', 'Cross-platform app development', 'Real-world UX testing'],
    ARRAY['Offline-sync and local-first patterns', 'Resilient client architectures'],
    ARRAY['Engineering team capacity', 'User-testing channels'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"Low to Moderate","politicalRisk":"Low to Moderate","financialAccess":"Moderate","businessOrientation":"Product-first, adoption-driven"}'::jsonb,
    8
  ),
(
    uuid_generate_v4(),
    'infrastructure-maintainer',
    'Infrastructure Maintainer',
    'Relay & Bridge Keeper',
    'Independent Operator / Small Collective',
    'builder',
    false,
    'Keeps the relays, bridges, indexers, and storage alive — the invisible labor everyone depends on and almost no one funds. Chronically under-resourced and quietly indispensable.',
    'They run the unglamorous machinery that makes "decentralized" actually work: the relays that pass messages, the bridges between networks, the storage that doesn''t disappear. When it works, no one notices; when it breaks, the whole ecosystem feels it. They carry a long-term load that funders rarely reward and founders rarely thank, and they hold real, underappreciated leverage — because if they walk away, large parts of the network simply go dark.',
    ARRAY['Reliability', 'Stewardship', 'Sustainability', 'Quiet competence'],
    ARRAY['Keep critical infrastructure running', 'Secure sustainable funding for maintenance', 'Distribute operational load so it isn''t fragile'],
    ARRAY['Must maintain uptime commitments', 'Bound by the dependencies others have built on them', 'Limited by personal/collective capacity'],
    ARRAY['Operations and reliability engineering', 'Incident response', 'Infrastructure hosting'],
    ARRAY['Operational runbooks', 'Reliability and monitoring tooling'],
    ARRAY['Maintainer hours (scarce)', 'Server and bandwidth capacity'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Low (high dependency on them)","politicalRisk":"Low","financialAccess":"Low","businessOrientation":"Maintenance-first, sustainability-seeking"}'::jsonb,
    9
  ),
(
    uuid_generate_v4(),
    'identity-privacy-cryptographer',
    'Identity & Privacy Cryptographer',
    'Self-Sovereign ID Builder',
    'Cryptography Lab',
    'builder',
    false,
    'Builds self-sovereign identity and strong privacy guarantees into the dweb. Holds a hard line on privacy that clashes with anyone needing transparency or legibility.',
    'They came up through privacy research and watched identity become the platform-State''s primary instrument of enclosure — the thing that ties a person to a territory they can be controlled within. Their work gives users portable, unlinkable, self-owned identity. That commitment is non-negotiable and frequently inconvenient: it complicates accountability, frustrates policy actors who need legibility, and resists the transparency that some governance and journalism roles depend on.',
    ARRAY['Privacy', 'Self-sovereignty', 'Cryptographic integrity', 'Autonomy'],
    ARRAY['Ship portable self-sovereign identity', 'Make privacy the default, not an option', 'Resist any re-introduction of identity-based enclosure'],
    ARRAY['Must not weaken cryptographic guarantees', 'Bound by formal security review', 'Cannot build in backdoors or surveillance hooks'],
    ARRAY['Applied cryptography', 'Identity protocol design', 'Privacy threat modeling'],
    ARRAY['Self-sovereign identity schemes', 'Zero-knowledge primitives and libraries'],
    ARRAY['Cryptographer attention', 'Audit and review bandwidth'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate to High (privacy under regulatory pressure)","financialAccess":"Moderate","businessOrientation":"Privacy-first, principle-driven"}'::jsonb,
    10
  ),
(
    uuid_generate_v4(),
    'hardware-mesh-networker',
    'Hardware / Mesh Networker',
    'Physical Layer Liberator',
    'Mesh & Device Cooperative',
    'builder',
    false,
    'Builds the physical layer — mesh nodes, off-grid radios, refurbished devices — that frees the dweb from the platform-State''s pipes and data centers.',
    'They understand that "decentralized" software running on three cloud providers and two undersea cables isn''t decentralized at all. Their work is the literal substrate of nomad infrastructure: networks that move with people, run off-grid, and answer to no carrier or hyperscaler. It''s slow, physical, capital-hungry work that doesn''t scale like software, but it''s the only thing that makes true exit from the platform-State possible rather than rhetorical.',
    ARRAY['Physical sovereignty', 'Resilience', 'Self-reliance', 'Decentralization-in-fact'],
    ARRAY['Build mesh networks independent of incumbent carriers', 'Get resilient hardware into nomadic communities', 'Prove the dweb can run on its own physical layer'],
    ARRAY['Bound by spectrum and hardware regulation', 'Must maintain physical deployments', 'Limited by manufacturing and logistics'],
    ARRAY['Mesh network deployment', 'Hardware design and refurbishment', 'Off-grid power and connectivity'],
    ARRAY['Open hardware designs', 'Mesh routing implementations'],
    ARRAY['Physical devices and components', 'Deployment crew time'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"Low","politicalRisk":"Moderate (spectrum/regulatory exposure)","financialAccess":"Low to Moderate (capital-intensive)","businessOrientation":"Infrastructure-in-fact, cooperative"}'::jsonb,
    11
  ),
(
    uuid_generate_v4(),
    'stealth-platform-defector',
    'Stealth Platform Defector',
    'Reformed Hyperscaler Engineer',
    'Ex-Big-Tech Principal Engineer',
    'builder',
    true,
    'An elite engineer who left a dominant platform to build the dweb. Brings world-class skills — and the deep, unexamined habits of centralization that built the platform-State.',
    'They can architect systems at a scale almost no one else in the room can, and they came to the dweb sincerely, disillusioned with what they helped build. The danger is in their reflexes: the defaults they reach for — a central coordinator "just for now," a managed service "for reliability," a metrics pipeline "to understand users" — are exactly the patterns that quietly recentralize a decentralized system. Their contribution is enormous and their instincts are a standing risk the others must watch.',
    ARRAY['Engineering excellence', 'Scale', 'Reliability', 'Redemption'],
    ARRAY['Build dweb systems that perform at platform scale', 'Apply hard-won infrastructure expertise to the cause', 'Outdo the platforms at their own game'],
    ARRAY['Bound by non-competes and IP from former employer', 'Must keep systems performant and reliable', 'Reputation tied to delivering at scale'],
    ARRAY['Large-scale systems architecture', 'Performance and reliability engineering', 'Deep platform-internals knowledge'],
    ARRAY['Scalable infrastructure patterns', 'High-performance system designs'],
    ARRAY['Rare senior-engineering capacity', 'Architectural decision influence'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"Moderate to High","politicalRisk":"Low to Moderate (former-employer exposure)","financialAccess":"Moderate to High","businessOrientation":"Excellence-driven, scale-oriented"}'::jsonb,
    12
  ),
(
    uuid_generate_v4(),
    'data-commons-engineer',
    'Data-Commons Engineer',
    'Shared Data Trust Builder',
    'Data Trust / Commons Project',
    'builder',
    false,
    'Builds shared data trusts and storage commons with governance baked in — so collectively-held data can''t be quietly enclosed. Powerful, principled, and slow.',
    'They treat data as the territory the platform-State most wants to enclose, and they build the alternative: pooled data held under explicit collective governance, with access rules, consent, and provenance enforced at the infrastructure level. The result is genuinely uncapturable shared data — and it is painstaking to build, because every technical decision is also a governance decision that the participating communities must actually agree to. Speed is the price of legitimacy.',
    ARRAY['Collective ownership', 'Consent', 'Provenance', 'Anti-enclosure'],
    ARRAY['Build governed data commons that resist capture', 'Embed consent and provenance in the data layer', 'Enable communities to pool data on their own terms'],
    ARRAY['Bound by participating communities'' governance', 'Must enforce consent and access rules', 'Cannot release data outside agreed terms'],
    ARRAY['Data-trust architecture', 'Access-control and provenance systems', 'Governance-aware engineering'],
    ARRAY['Data-commons governance frameworks', 'Consent and provenance tooling'],
    ARRAY['Engineering capacity', 'Governance-facilitation bandwidth'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate (data regulation exposure)","financialAccess":"Moderate","businessOrientation":"Commons-first, governance-heavy"}'::jsonb,
    13
  ),
(
    uuid_generate_v4(),
    'community-organizer',
    'Community Organizer',
    'Adoption Steward',
    'Grassroots Community Lead',
    'organizer',
    false,
    'Onboards and represents an actual, living user community on the dweb. Holds the legitimacy and adoption everyone else needs — and deeply distrusts technocratic capture.',
    'They built their community the slow way: trust, showing up, solving real problems, year after year. That community is now exactly the prize that builders, funders, and marketers all want a piece of — a real population of users, not a projection on a pitch deck. The organizer guards that legitimacy fiercely, because they''ve watched communities get used as growth fuel and then abandoned. Any agreement that touches their people has to clear a high bar of reciprocity.',
    ARRAY['Community sovereignty', 'Reciprocity', 'Trust', 'Bottom-up power'],
    ARRAY['Get the community onto durable, non-extractive infrastructure', 'Ensure the community shapes the tools it uses', 'Protect members from capture and extraction'],
    ARRAY['Accountable to community members first', 'Must maintain trust earned over years', 'Cannot commit the community without its consent'],
    ARRAY['Community mobilization', 'Onboarding and education', 'On-the-ground feedback channels'],
    ARRAY['Organizing and onboarding playbooks', 'Community trust relationships'],
    ARRAY['An actual user base (highly sought)', 'Organizer time and credibility'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate (high within community)","politicalRisk":"Low to Moderate","financialAccess":"Low","businessOrientation":"Community-first, non-extractive"}'::jsonb,
    14
  ),
(
    uuid_generate_v4(),
    'migrant-nomad-user-advocate',
    'Migrant / Nomad User Advocate',
    'Voice of the Displaced',
    'User Advocacy Collective',
    'organizer',
    false,
    'Speaks for the displaced, on-the-move users at the heart of the scenario — people pushed into nomad patterns by enclosure. Needs accessibility and resilience above all.',
    'Their constituency is the population the whole game is nominally for: people whose digital lives have been disrupted, deplatformed, or pushed across borders by the platform-State''s vectors of enclosure. They translate the lived needs of those users — intermittent connectivity, low-cost devices, no stable address, high surveillance risk — into demands on builders who might otherwise design for themselves. They''re a conscience and a constraint: a beautiful protocol that the displaced can''t actually use fails the entire premise.',
    ARRAY['Accessibility', 'Dignity', 'Resilience', 'Inclusion'],
    ARRAY['Make the dweb usable for the genuinely displaced', 'Keep accessibility and cost central to design', 'Ensure nomadic users aren''t an afterthought'],
    ARRAY['Accountable to a vulnerable constituency', 'Must represent needs faithfully, not romanticize', 'Bound by the real constraints of users'' lives'],
    ARRAY['User-needs research with hard-to-reach populations', 'Accessibility advocacy', 'Trust within displaced communities'],
    ARRAY['Lived-needs research and personas', 'Accessibility requirement frameworks'],
    ARRAY['Access to and trust of displaced users', 'Advocacy bandwidth'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Low","politicalRisk":"Moderate (constituency is politically exposed)","financialAccess":"Low","businessOrientation":"Advocacy-first, access-driven"}'::jsonb,
    15
  ),
(
    uuid_generate_v4(),
    'cooperative-operator',
    'Cooperative Operator',
    'Worker & Data Co-op Lead',
    'Platform Cooperative',
    'organizer',
    false,
    'Runs a worker- and data-owned cooperative already using dweb tools in production. Wants interoperability — strictly on the co-op''s own democratic governance terms.',
    'Their cooperative is living proof that an alternative to the platform-State can pay people''s rent: members own the platform, the data, and the surplus. Because it actually works and actually sustains livelihoods, they have hard requirements no idealist can wave away. They''ll integrate with the wider dweb, but never in a way that compromises member ownership or hands governance to outsiders. They are a model and a tough negotiator, bringing a working example and a non-negotiable bottom line.',
    ARRAY['Worker ownership', 'Democratic governance', 'Sustainability', 'Solidarity'],
    ARRAY['Interoperate with the dweb without losing autonomy', 'Demonstrate cooperatives as a durable model', 'Federate with aligned co-ops'],
    ARRAY['Bound by cooperative bylaws and member votes', 'Must protect member livelihoods', 'Cannot cede governance to external parties'],
    ARRAY['Cooperative governance', 'Running production services sustainably', 'Member-driven product development'],
    ARRAY['Platform-cooperative governance models', 'Federated co-op protocols'],
    ARRAY['A working co-op others want to integrate with', 'Member labor and attention'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Low","financialAccess":"Moderate (revenue-generating)","businessOrientation":"Cooperative, member-owned"}'::jsonb,
    16
  ),
(
    uuid_generate_v4(),
    'local-node-host-steward',
    'Local Node Host / Steward',
    'Ground Infrastructure Keeper',
    'Community Hub Operator',
    'organizer',
    false,
    'Runs community-facing dweb infrastructure in a physical place — a local node, hub, or hackerspace — bridging the digital network and the people who live around it.',
    'They host the box in the back room: the local relay, the community server, the mesh node on the roof. They''re the human face of the dweb in one specific place, the person neighbors actually ask when something breaks. They translate global infrastructure into local reality and back again, carrying both the technical duty of keeping a node up and the social duty of keeping a community included. Their leverage is locality — they hold a real foothold in physical territory that purely digital actors can''t reach.',
    ARRAY['Place', 'Stewardship', 'Local resilience', 'Inclusion'],
    ARRAY['Keep local infrastructure running and accessible', 'Bridge digital network and physical community', 'Federate with other local nodes'],
    ARRAY['Accountable to local users', 'Must maintain physical and digital uptime', 'Bound by local context and constraints'],
    ARRAY['Local node operation', 'Community tech support', 'Physical-space hosting'],
    ARRAY['Local-node setup guides', 'Community-hub operating models'],
    ARRAY['Physical space and local presence', 'Steward time'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Low (high locally)","politicalRisk":"Low to Moderate","financialAccess":"Low","businessOrientation":"Place-based, community-first"}'::jsonb,
    17
  ),
(
    uuid_generate_v4(),
    'platform-refugee-influencer',
    'Platform-Refugee Influencer',
    'Migrated-Audience Magnet',
    'Independent Creator',
    'organizer',
    true,
    'Fled a collapsing platform and brought a huge audience to the dweb. Delivers users at a scale organizers can only dream of — along with platform-era expectations and drama.',
    'When their old platform turned hostile, they left and a large slice of their audience followed, making them one of the fastest on-ramps to dweb adoption in the room. But the audience came shaped by platform logic: they expect frictionless feeds, constant novelty, monetization, and the parasocial intensity that platforms engineered. The influencer can flood a project with users overnight — and just as easily import the engagement-maximizing, drama-driven dynamics that the dweb is supposed to be an escape from.',
    ARRAY['Reach', 'Authenticity (as brand)', 'Audience loyalty', 'Momentum'],
    ARRAY['Establish a durable home for the audience on the dweb', 'Convert reach into real adoption', 'Maintain relevance through the migration'],
    ARRAY['Beholden to audience expectations', 'Must keep producing to retain reach', 'Reputation tied to the migration succeeding'],
    ARRAY['Mass audience mobilization', 'Content production at volume', 'Trend-setting'],
    ARRAY['Audience relationship and brand', 'Content formats and back-catalog'],
    ARRAY['A large migratable audience (rare, coveted)', 'Their own attention and posting cadence'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"Moderate (audience-derived)","politicalRisk":"Moderate (deplatforming-prone)","financialAccess":"Moderate (monetization-dependent)","businessOrientation":"Reach-driven, creator-economy"}'::jsonb,
    18
  ),
(
    uuid_generate_v4(),
    'indigenous-data-sovereignty-practitioner',
    'Indigenous Data-Sovereignty Practitioner',
    'Collective-Rights Guardian',
    'Indigenous Data Governance Body',
    'organizer',
    false,
    'Stewards community data under collective, rather than individual, rights frameworks. Brings non-negotiable boundaries rooted in sovereignty that long predates the internet.',
    'They operate from a tradition in which data about a people belongs to that people collectively, governed by their own law and protocols — a framework like the CARE principles that the dominant individual-consent model simply cannot express. They''ve seen "open" and "decentralized" projects extract and expose community knowledge under the banner of freedom. They will collaborate, but only on terms that honor collective authority and the right to say no, and that boundary is not a bargaining position — it''s the precondition for any agreement at all.',
    ARRAY['Collective sovereignty', 'Self-determination', 'Reciprocity', 'Stewardship'],
    ARRAY['Ensure community data is governed by the community', 'Embed collective-rights frameworks into the dweb', 'Protect knowledge from extraction'],
    ARRAY['Bound by community law and protocol', 'Cannot share governed knowledge without collective consent', 'Accountable to the community''s authority'],
    ARRAY['Collective data governance', 'Indigenous protocol expertise', 'Trust-based partnership building'],
    ARRAY['Collective-rights data frameworks (e.g. CARE-aligned)', 'Community governance protocols'],
    ARRAY['Stewarded knowledge and access to it', 'Practitioner time and trust'],
    '{"riskTolerance":"Low","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate","financialAccess":"Low to Moderate","businessOrientation":"Sovereignty-first, reciprocal"}'::jsonb,
    19
  ),
(
    uuid_generate_v4(),
    'documentarian-filmmaker',
    'Documentarian / Filmmaker',
    'Movement Chronicler',
    'Independent Documentary Maker',
    'storyteller',
    false,
    'Captures and legitimizes the dweb movement on film. Controls how the story reaches the wider world — and needs access and authentic material to do it.',
    'They believe a movement that isn''t documented effectively didn''t happen as far as the wider world is concerned, and they''ve trained their lens on the dweb because they think it''s the most important infrastructure story of the era. Their film can grant legitimacy, attract funders, and move public opinion. But they need genuine access to make something true rather than promotional, which means earning the trust of organizers and builders who are wary of being flattened into a narrative or exposed before they''re ready.',
    ARRAY['Truth', 'Legitimacy through story', 'Access', 'Craft'],
    ARRAY['Document the movement credibly and at reach', 'Bring outside attention and legitimacy', 'Preserve a truthful record of how it happened'],
    ARRAY['Bound by documentary ethics', 'Must protect vulnerable subjects', 'Accountable to distributors/funders of the film'],
    ARRAY['Filmmaking and storytelling', 'Access to distribution and audiences', 'Legitimacy-conferring narrative'],
    ARRAY['Footage and the film itself', 'Narrative and access relationships'],
    ARRAY['Production capacity and timeline', 'Distribution and attention'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate (subjects may be exposed)","financialAccess":"Low to Moderate","businessOrientation":"Narrative-driven, mission-aligned"}'::jsonb,
    20
  ),
(
    uuid_generate_v4(),
    'visual-artist-world-builder',
    'Visual Artist / World-Builder',
    'Aesthetic Infrastructure Designer',
    'Independent Artist / Studio',
    'storyteller',
    false,
    'Gives the movement a visual language and identity — the symbols, worlds, and aesthetics that make an abstract idea feel real and worth belonging to.',
    'They argue that aesthetics are infrastructure: people don''t join protocols, they join worlds they can see and feel themselves inside. Their illustrations, type, motifs, and imagined futures do the work of making "decentralized web" into something with a face, a vibe, a flag people will rally to. This makes them quietly powerful — the dominant visual language shapes which projects feel legitimate and alive — and it puts them in tension with anyone who thinks the "real" work is purely technical.',
    ARRAY['Beauty', 'Meaning', 'Belonging', 'Imagination'],
    ARRAY['Build a coherent visual identity for the movement', 'Make the dweb feel like a world people want to inhabit', 'Translate abstract values into images'],
    ARRAY['Must stay true to the movement''s values', 'Bound by commissions and collaborations', 'Accountable to communities whose identity they shape'],
    ARRAY['Visual design and illustration', 'World-building and identity systems', 'Aesthetic direction'],
    ARRAY['Visual language, motifs, and assets', 'World-building canon'],
    ARRAY['Artist time and creative output', 'Aesthetic legitimacy (whose look wins)'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Low to Moderate","politicalRisk":"Low","financialAccess":"Low to Moderate","businessOrientation":"Identity-driven, mission-aligned"}'::jsonb,
    21
  ),
(
    uuid_generate_v4(),
    'independent-journalist-investigator',
    'Independent Journalist / Investigator',
    'Accountability Press',
    'Independent Reporter',
    'storyteller',
    false,
    'Covers the dweb with a critical eye, holding even the movement''s heroes accountable. Trusted precisely because they''ll report inconvenient truths.',
    'They came to the beat believing decentralization is worth defending — and that the surest way to discredit it is to let its failures and hypocrisies go unexamined until an enemy finds them first. They scrutinize the funders'' strings, the "decentralized" systems quietly running on three cloud providers, the governance that concentrates power while claiming not to. Their reporting builds credibility for the whole movement, but their willingness to expose problems makes them an uneasy partner for anyone with something to hide.',
    ARRAY['Truth', 'Accountability', 'Independence', 'Public interest'],
    ARRAY['Hold the movement to its own stated values', 'Expose recentralization and extraction early', 'Build public credibility through honest coverage'],
    ARRAY['Bound by journalistic ethics', 'Must verify before publishing', 'Must protect sources'],
    ARRAY['Investigation and verification', 'Reaching public audiences', 'Source networks'],
    ARRAY['Reporting and investigative findings', 'Source relationships'],
    ARRAY['Reporting time and editorial space', 'Credibility (spent if misused)'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate to High","financialAccess":"Low","businessOrientation":"Public-interest, independent"}'::jsonb,
    22
  ),
(
    uuid_generate_v4(),
    'archivist-memory-keeper',
    'Archivist / Memory-Keeper',
    'Anti-Erasure Custodian',
    'Distributed Archive Project',
    'storyteller',
    false,
    'Preserves the movement''s record — its decisions, culture, and history — against erasure. Lives in the tension between permanence and the right to disappear.',
    'They know the platform-State''s quietest weapon is the memory hole: things vanish, history is rewritten, and no one can prove what was promised. They build durable, distributed archives so the dweb''s commitments, debates, and culture survive. But permanence cuts both ways — the same durability that defends against erasure collides directly with the privacy cryptographer''s right-to-disappear and with communities that don''t want their knowledge fixed forever. They hold the past, and holding it is itself contested.',
    ARRAY['Permanence', 'Memory', 'Truth over time', 'Resilience'],
    ARRAY['Preserve the movement''s record durably', 'Prevent silent erasure and revision', 'Make history verifiable and accessible'],
    ARRAY['Must preserve faithfully and neutrally', 'Bound to honor consent and removal where promised', 'Accountable to future users, not just present ones'],
    ARRAY['Distributed archiving', 'Provenance and integrity verification', 'Long-term preservation'],
    ARRAY['The archive itself', 'Preservation and provenance methods'],
    ARRAY['Storage and curation capacity', 'Archivist attention'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate (preservation vs. privacy conflict)","financialAccess":"Low","businessOrientation":"Preservation-first, public-interest"}'::jsonb,
    23
  ),
(
    uuid_generate_v4(),
    'attention-broker',
    'Attention Broker',
    'Growth-Hacking Marketer',
    'Growth Marketing Operator',
    'storyteller',
    true,
    'Can 10x a project''s adoption through tactics honed inside the platform-State — virality engines, referral loops, engagement hooks — the very mechanics the dweb is trying to escape.',
    'They are genuinely on the dweb''s side and genuinely effective, which is exactly what makes them dangerous. They know how to make anything spread because they spent years building the growth machines of the platforms. Offered a dweb project, they can deliver users at a rate no organic organizer can match. The cost is in the methods: the dark patterns, the manufactured urgency, the optimization for engagement over wellbeing — importing the platform-State''s logic into the thing meant to replace it.',
    ARRAY['Growth', 'Reach', 'Conversion', 'Momentum'],
    ARRAY['Drive rapid, measurable adoption', 'Make dweb projects spread virally', 'Prove the dweb can win on growth, not just principle'],
    ARRAY['Accountable to growth targets', 'Bound by client/project mandates', 'Reputation tied to numbers going up'],
    ARRAY['Viral and growth-loop design', 'Conversion optimization', 'Channel and campaign execution'],
    ARRAY['Growth playbooks and funnels', 'Engagement-mechanic designs'],
    ARRAY['Marketing budget and channels', 'Their own execution capacity'],
    '{"riskTolerance":"High","institutionalTrust&Power":"Low to Moderate","politicalRisk":"Low","financialAccess":"Moderate","businessOrientation":"Growth-driven, results-first"}'::jsonb,
    24
  ),
(
    uuid_generate_v4(),
    'sound-music-performance-artist',
    'Sound / Music & Performance Artist',
    'Movement''s Affective Glue',
    'Musician / Performance Collective',
    'storyteller',
    false,
    'Creates the music, sound, and live performance that turn a network into a culture and a gathering into a movement. The affective glue that makes people feel they belong.',
    'They understand that movements are held together less by arguments than by shared feeling — the song everyone knows, the set that turns a roomful of strangers into a we. Their work at gatherings like DWeb Camp is what converts abstract alignment into embodied solidarity. It''s hard to value in a spreadsheet and easy to overlook, but without it the dweb is a set of protocols no one feels anything about. They trade in belonging, which is both real and notoriously hard to put terms on.',
    ARRAY['Belonging', 'Feeling', 'Collective joy', 'Presence'],
    ARRAY['Turn the network into a felt culture', 'Energize gatherings and sustain morale', 'Make solidarity something people experience, not just agree to'],
    ARRAY['Must show up and perform live', 'Bound by collaborations and venues', 'Accountable to the communities they move'],
    ARRAY['Music and sound creation', 'Live performance', 'Atmosphere and ritual design'],
    ARRAY['Original music and performances', 'Ritual and gathering formats'],
    ARRAY['Performance time and energy', 'Presence at gatherings (can''t be everywhere)'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Low","politicalRisk":"Low","financialAccess":"Low","businessOrientation":"Culture-first, presence-driven"}'::jsonb,
    25
  ),
(
    uuid_generate_v4(),
    'nomad-theory-philosopher',
    'Nomad-Theory Philosopher',
    'Frame-Giver',
    'Independent Theorist',
    'strategist',
    false,
    'Supplies the conceptual frame for the whole endeavor — smooth versus striated space, movement as territory, the platform-State as enclosure. Generative, and capable of stalling action.',
    'They are the one who can name what''s actually happening: that the platform-State is a _mode_ that restricts other modes, that nomads hold territory through trajectory rather than settlement. Their concepts give the movement its self-understanding and its language for refusing false solutions. But the gift has a shadow — a perfectly framed problem can become a reason never to ship, and their pursuit of conceptual rigor sometimes pulls a room away from the imperfect agreement that would actually build something.',
    ARRAY['Conceptual clarity', 'Refusal of enclosure', 'Critique', 'Imagination'],
    ARRAY['Give the movement a coherent frame to act from', 'Guard against solutions that recreate the platform-State', 'Open new directions others can''t yet see'],
    ARRAY['Must remain intellectually honest', 'Accountable to the coherence of the frame', 'Bound by their own critique of power'],
    ARRAY['Conceptual framing', 'Critique and diagnosis', 'Generating new directions'],
    ARRAY['Theoretical frameworks and vocabulary', 'Critical analyses'],
    ARRAY['Attention and airtime in deliberation', 'Their own thinking time'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Low to Moderate","politicalRisk":"Low","financialAccess":"Low","businessOrientation":"Idea-driven, non-commercial"}'::jsonb,
    26
  ),
(
    uuid_generate_v4(),
    'public-interest-policy-strategist',
    'Public-Interest Policy Strategist',
    'Regulatory Edge-Worker',
    'Policy Advocacy Organization',
    'strategist',
    false,
    'Works the regulatory edges to protect the dweb legally and win it room to grow — which means demanding legibility the autonomy and privacy camps resist.',
    'They operate where the movement meets the law, translating between worlds that barely trust each other. They know the dweb needs legal cover to survive the platform-State''s regulatory capture, and they can win exemptions, safe harbors, and standing. But the price of legal protection is almost always legibility — disclosure, accountability, identifiable parties — which runs straight into the cryptographers'' privacy guarantees and the philosophers'' refusal of enclosure. They''re indispensable and perpetually accused of inviting the State back in through the side door.',
    ARRAY['Legal durability', 'Pragmatism', 'Public interest', 'Strategic protection'],
    ARRAY['Win legal room for the dweb to operate', 'Pre-empt hostile regulation', 'Translate movement needs into policy wins'],
    ARRAY['Bound by what''s legally achievable', 'Accountable to coalition partners', 'Must operate within the law to change it'],
    ARRAY['Policy analysis and drafting', 'Regulatory relationships', 'Coalition building'],
    ARRAY['Policy frameworks and model legislation', 'Regulatory strategy'],
    ARRAY['Policy-staff time', 'Access to regulators and lawmakers'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"Moderate to High","politicalRisk":"Moderate","financialAccess":"Moderate","businessOrientation":"Public-interest, pragmatic"}'::jsonb,
    27
  ),
(
    uuid_generate_v4(),
    'standards-governance-diplomat',
    'Standards & Governance Diplomat',
    'Faction Mediator',
    'Neutral Coordination Body',
    'strategist',
    false,
    'Mediates between protocols, projects, and factions toward shared governance. A trusted broker — with influence but little hard enforcement power.',
    'They''ve made a vocation of the space between camps, brokering the agreements that let rival implementations interoperate and feuding communities share standards. Their power is entirely soft: trust, neutrality, and the ability to get adversaries in a room and keep them there. They can author a governance process everyone signs, but they can''t make anyone obey it, which means their every success depends on the continued goodwill of parties who could walk at any time. They hold the ecosystem''s coordination together by reputation alone.',
    ARRAY['Coordination', 'Neutrality', 'Polycentric governance', 'Interdependence'],
    ARRAY['Get rival factions to shared governance', 'Keep protocols interoperable', 'Build durable, legitimate coordination processes'],
    ARRAY['Must remain credibly neutral', 'Cannot favor any faction', 'Bound by the agreements they broker'],
    ARRAY['Multi-party mediation', 'Governance process design', 'Trust-brokering'],
    ARRAY['Governance process templates', 'Mediation frameworks'],
    ARRAY['Neutral credibility (fragile)', 'Mediation bandwidth'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate to High","politicalRisk":"Moderate","financialAccess":"Moderate","businessOrientation":"Coordination-first, neutral"}'::jsonb,
    28
  ),
(
    uuid_generate_v4(),
    'memetic-strategist',
    'Memetic Strategist',
    'Perception Engineer',
    'Narrative Strategy Operator',
    'strategist',
    false,
    'Shapes how the movement is perceived at the meta-level — the framings, slogans, and memes that decide which ideas spread and which die. Story as strategy, not decoration.',
    'Where the visual artist builds a world to inhabit and the marketer drives a funnel, this strategist works one level up: on the contest of meaning itself. They decide whether the dweb is framed as "freedom" or "chaos," whether enclosure is named and felt, whether a rival''s narrative is neutralized before it lands. They wield real power over the discourse and operate close to the line where persuasion becomes manipulation — a line the journalist and philosopher will hold them to.',
    ARRAY['Narrative power', 'Framing', 'Resonance', 'Strategic clarity'],
    ARRAY['Win the contest of meaning around the dweb', 'Make the movement''s framing spread and stick', 'Neutralize hostile narratives'],
    ARRAY['Accountable to the movement''s actual values', 'Must not cross into disinformation', 'Bound by reputational risk if exposed as manipulation'],
    ARRAY['Narrative and framing strategy', 'Meme and message design', 'Discourse analysis'],
    ARRAY['Framing and narrative playbooks', 'Memetic strategy'],
    ARRAY['Strategist attention', 'Narrative airtime and channels'],
    '{"riskTolerance":"Moderate to High","institutionalTrust&Power":"Low to Moderate","politicalRisk":"Moderate","financialAccess":"Low to Moderate","businessOrientation":"Narrative-driven, strategic"}'::jsonb,
    29
  ),
(
    uuid_generate_v4(),
    'economic-tokenomics-designer',
    'Economic / Tokenomics Designer',
    'Incentive Architect',
    'Mechanism Design Practitioner',
    'strategist',
    false,
    'Designs the incentive structures and value flows that make a dweb economy sustainable — mathematically elegant systems that are sometimes socially blunt.',
    'They believe most decentralized projects don''t fail technically, they fail economically: the incentives quietly reward the wrong behavior until the whole thing hollows out. Their mechanisms — bonding curves, staking, fee flows, retroactive rewards — can make cooperation rational and sustainability automatic. The risk is in mistaking the model for the people: a beautifully balanced incentive system can still grind against the lived values of an organizer''s community or a co-op''s bylaws, optimizing a number while corroding the thing it was meant to serve.',
    ARRAY['Sustainability', 'Aligned incentives', 'Rigor', 'Mechanism integrity'],
    ARRAY['Design economies that sustain dweb infrastructure', 'Make cooperation the rational default', 'Avoid extractive or degenerate incentive loops'],
    ARRAY['Must model honestly, including failure modes', 'Accountable to communities adopting the design', 'Bound by the math holding up under stress'],
    ARRAY['Mechanism and incentive design', 'Economic modeling and simulation', 'Token and fee architecture'],
    ARRAY['Incentive-mechanism designs', 'Economic models and simulations'],
    ARRAY['Design and modeling time', 'Adoption of their mechanism (only so many can dominate)'],
    '{"riskTolerance":"Moderate","institutionalTrust&Power":"Moderate","politicalRisk":"Moderate (regulatory exposure of token models)","financialAccess":"Moderate","businessOrientation":"Mechanism-first, sustainability-driven"}'::jsonb,
    30
  ),
(
    uuid_generate_v4(),
    'futures-forecaster-think-tank-fellow',
    'Futures Forecaster / Think-Tank Fellow',
    'Agenda-Setter',
    'Influential Research Institute',
    'strategist',
    true,
    'Shapes which futures the movement and its funders take seriously through influential foresight work. Whoever frames the future quietly steers the funding.',
    'They publish the scenarios, roadmaps, and "state of the dweb" reports that funders, policymakers, and press treat as the map of where things are going. That map is never neutral — every forecast elevates some priorities and buries others, and their institute has its own backers whose interests tint the lens. They sincerely want the dweb to flourish, but their power to set the agenda means a single influential report can redirect capital and attention toward their preferred future and away from paths that might have served the commons better.',
    ARRAY['Foresight', 'Influence', 'Strategic positioning', 'Credibility'],
    ARRAY['Shape the movement''s sense of where it''s going', 'Direct attention and capital toward favored futures', 'Cement the institute as the authoritative voice'],
    ARRAY['Bound by the institute''s funders and mandate', 'Must maintain a credible appearance of rigor', 'Reputation tied to forecasts not aging badly'],
    ARRAY['Foresight and scenario research', 'Convening funders and policymakers', 'Agenda-setting publication'],
    ARRAY['Forecasts, scenarios, and reports', 'Institutional credibility and platform'],
    ARRAY['Authoritative airtime (whose forecast leads)', 'Researcher and convening capacity'],
    '{"riskTolerance":"Low to Moderate","institutionalTrust&Power":"High","politicalRisk":"Low to Moderate","financialAccess":"Moderate to High (funder-dependent)","businessOrientation":"Influence-driven, institutional"}'::jsonb,
    31
  );
